trigger:
- main  # Ersetze dies durch den Branch, den du verwenden möchtest

pool:
  default

variables:
  solution: '**/*.sln'  # Der Pfad zu deiner .sln-Datei
  buildConfiguration: 'Release'  # Konfiguration, die verwendet werden soll

steps:

- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '8.x'
- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    projects: '$(solution)'  # Wiederherstellung der NuGet-Pakete
- task: DotNetCoreCLI@2
  inputs:
    azureSubscription: 'Azure subscription 1(1)(9502841d-29c3-4212-bf50-32ed5e37619c)'
    command: 'publish'
    publishWebProjects: true
    

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '$(solution)'
    arguments: '--configuration $(buildConfiguration)'  # Anwendung im Release-Modus bauen

- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    projects: '$(solution)'
    arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'  # Veröffentlichen der Anwendung

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'  # Name des veröffentlichten Artefakts
