trigger: none  # Keine automatischen Trigger, nur manuell starten

pool:
  vmImage: 'windows-latest'  # Verwende das Windows-Image

jobs:
  - job: Build
    displayName: "Build Blazor WebAssembly Project"
    steps:
      - task: DotNetCoreCLI@2
        inputs:
          command: 'build'  # Befehl für den Build
          projects: '**/*.csproj'  # Pfad zu den .csproj-Dateien
          configuration: 'Release'  # Konfiguration, die verwendet werden soll
